-- Baseline: schema as it existed under `spring.jpa.hibernate.ddl-auto=update`
-- immediately before Flyway was introduced (i.e. before the GameType/GameEngine
-- work in this changeset). Captured from the live dev database so Hibernate's
-- `validate` mode has an exact match to check against. V2 layers on the
-- `game_type` column added alongside this baseline.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(32)  NOT NULL,
    email           VARCHAR(128) NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(64),
    role            VARCHAR(32)  NOT NULL,
    wallet_balance  NUMERIC(19,2),
    is_active       BOOLEAN NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(128) NOT NULL,
    user_id     BIGINT NOT NULL,
    revoked     BOOLEAN NOT NULL,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_tokens_token UNIQUE (token),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE game_rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_code     VARCHAR(12) NOT NULL,
    name          VARCHAR(64),
    max_players   INTEGER NOT NULL,
    stake_amount  NUMERIC(19,2),
    game_variant  VARCHAR(16),
    status        VARCHAR(16) NOT NULL,
    created_by    BIGINT,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_game_rooms_room_code UNIQUE (room_code),
    CONSTRAINT chk_game_rooms_game_variant CHECK (game_variant IN ('POOL_101', 'POOL_201', 'POINTS')),
    CONSTRAINT chk_game_rooms_status CHECK (status IN ('WAITING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT fk_game_rooms_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE room_players (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    seat_number  INTEGER,
    status       VARCHAR(16) NOT NULL,
    score        INTEGER,
    joined_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    left_at      TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT uk_room_players_room_user UNIQUE (room_id, user_id),
    CONSTRAINT chk_room_players_status CHECK (status IN ('JOINED', 'READY', 'PLAYING', 'DROPPED', 'LEFT')),
    CONSTRAINT fk_room_players_room FOREIGN KEY (room_id) REFERENCES game_rooms (id),
    CONSTRAINT fk_room_players_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE game_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id     BIGINT NOT NULL,
    winner_id   BIGINT,
    status      VARCHAR(16) NOT NULL,
    total_pot   NUMERIC(19,2),
    started_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    ended_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT chk_game_sessions_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'ABORTED')),
    CONSTRAINT fk_game_sessions_room FOREIGN KEY (room_id) REFERENCES game_rooms (id),
    CONSTRAINT fk_game_sessions_winner FOREIGN KEY (winner_id) REFERENCES users (id)
);

CREATE TABLE game_moves_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    move_type    VARCHAR(16) NOT NULL,
    move_data    OID,
    sequence_no  BIGINT,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_game_moves_log_move_type CHECK (move_type IN ('DRAW_CLOSED', 'DRAW_OPEN', 'DISCARD', 'DECLARE', 'DROP', 'JOIN', 'LEAVE')),
    CONSTRAINT fk_game_moves_log_session FOREIGN KEY (session_id) REFERENCES game_sessions (id),
    CONSTRAINT fk_game_moves_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE wallet_transactions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    type                  VARCHAR(16) NOT NULL,
    amount                NUMERIC(19,2) NOT NULL,
    balance_after         NUMERIC(19,2) NOT NULL,
    reference_room_code   VARCHAR(12),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_wallet_transactions_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'STAKE_DEBIT', 'STAKE_PAYOUT')),
    CONSTRAINT fk_wallet_transactions_user FOREIGN KEY (user_id) REFERENCES users (id)
);
